name: lottogenerator_v4
description: Lotto App
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/spin_fast.mp3
    - assets/sounds/spin_slow.mp3
    - assets/sounds/snake_eat.mp3
    - assets/sounds/snake_exit.mp3
    - assets/sounds/spin_stop.mp3
    - assets/sounds/spinner-sound-36693.mp3
